#! /usr/bin/env sh

# This script is run as the default command INSIDE the container
# and therfore does not need to issue commands via `docker-compose`

knex migrate:rollback
knex migrate:latest
knex seed:run
nodemon index.js
